name: Release (npmjs)

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with: { version: 10 }
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
          registry-url: https://registry.npmjs.org

      - run: pnpm install --frozen-lockfile
      - run: pnpm build-package

      - name: Check tag matches package.json version
        run: |
          TAG="${GITHUB_REF#refs/tags/v}"
          PKG=$(node -p "require('./package.json').version")
          [ "$TAG" = "$PKG" ] || { echo "Tag v$TAG != package.json $PKG"; exit 1; }

      - name: Configure npm auth (npmjs)
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          set -euxo pipefail
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          npm config get registry                 # debe ser https://registry.npmjs.org/
          npm whoami                              # debe imprimir: anjapadu
          test "$(npm whoami)" = "anjapadu"
          npm view $(node -p "require('./package.json').name") || true
          npm pack --dry-run

      # primero sin provenance para aislar errores de auth/permiso
      - name: Publish to npmjs
        run: pnpm publish --access public --no-git-checks --loglevel verbose
